server:
  port: 8080

spring:
#  profiles:
#    active: prod
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blank?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池的配置信息
      # 初始化建立的连接数，最小连接数，最大连接数
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间（获取连接最大等待时间，单位：毫秒）
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      # 是否缓存preparedStatement
      poolPreparedStatements: true
      # 最大preparedStatement缓存数，当pool-prepared-statements=true时需要大于0
      maxPoolPreparedStatementPerConnectionSize: 20
      # 检测连接是否失效的sql
      validation-query: SELECT 'x'
      # 检测连接是否失效的超时时间，单位：秒
      validation-query-timeout: 2
      # Spring aop监控的包路径
      aop-patterns: com.ideapro.blank.service.*
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter（数据库连接池监控统计插件）
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet（数据库连接池监控页面插件）
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1,192.168.1.6
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456

mybatis:
  configuration:
    use-generated-keys: true
    use-column-label: true
#    数据库表列：user_name
#    实体类属性：user_name
#
#    但是java中一般使用驼峰命名
#    数据库表列：user_name
#    实体类属性：userName
    map-underscore-to-camel-case: true
  type-aliases-package:
  mapper-locations: classpath:mappers/*.xml

#打印SQL
logging:
  level:
    com.ideapro.blank.repository: debug

# swagger(生产环境下true改为false)
swagger:
  enable: true
